1. Write a Python Program to Add Two Matrices?

In [3]:
import numpy as np
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[3,4]])
print(arr1+arr2)

[[2 4]
 [6 8]]


2. Write a Python Program to Multiply Two Matrices?

In [4]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[3,4]])
print(arr1*arr2)

[[ 1  4]
 [ 9 16]]


3. Write a Python Program to Transpose a Matrix?

In [7]:
arr1 = np.array([[1,2],[3,4]])
print(arr1.transpose())

[[1 3]
 [2 4]]


4. Write a Python Program to Sort Words in Alphabetic Order?

In [8]:
l = ['hgj','hguy','ewr','tuyu']
l.sort()
l

['ewr', 'hgj', 'hguy', 'tuyu']

5. Write a Python Program to Remove Punctuation From a String?

In [11]:
s = 'kumarimansi42@gmail.com#45$%^*'
punc = '''!'@#$%^&*()_+\,<>?[]{}()-+~`"'''
for i in s.lower():
    if i in punc:
        s = s.replace(i,"")
print(s)

kumarimansi42gmail.com45
